# Use the dasymetrically-interpolated population rasters generated by
# stage1_binary_dasymetric_interpolation.R to generate population density
# rasters
#
# Contact: Edgar Castro <edgar_castro@g.harvard.edu>

library(stringr)
library(terra)

terraOptions(tempdir = "temp/")

statefps <- str_extract(Sys.glob("output/bd-pops/*_population_2000.tif"), "[0-9]+")

args <- commandArgs(trailingOnly=TRUE)
if (length(args) > 0) {
  if (!args[1] %in% statefps) {
    stop(sprintf("Unsupported state FIPS code %s", args[1]))
  }
  statefps <- args[1]
}

for (statefp in statefps) {
  output_file <- sprintf("output/bd-pops/%s_population_2000.tif", statefp)
  if (file.exists(output_file)) {
    message(sprintf("Skipping state with FIPS code %s", statefp))
  } else {
    message(sprintf("Processing state with FIPS code %s", statefp))
    
    message("* Reading population raster")
    population_raster <- rast(sprintf("output/bd-pops/%s_population_2000.tif", statefp))
    
    cell_area_sq_meters <- prod(res(population_raster))
    
    cell_area_sq_mi <- cell_area_sq_meters / 1609.344 / 1609.344
    
    message("* Calculating population densities")
    population_density_raster <- population_raster / cell_area_sq_mi
    
    message("* Writing population raster")
    writeRaster(population_density_raster, output_file)
  }
}